version: '3'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql-clinic/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5431:5432
  app:
    image: app
    command: python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    build: ./
    tty: true
    restart: always
    depends_on:
      - db
    volumes:
      - ./.project/static/:/app/storage/
      - .:/code

volumes:
  postgres_data:
