# Generated by Django 3.1.3 on 2021-09-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210902_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'LOW'), ('2', 'MEDIUM'), ('3', 'HIGH')], default='1', max_length=6, verbose_name='priority'),
        ),
    ]
